blog/urls.py
from django.urls import path, include
from.import views

app_name='blog'

urlpatterns = [
    path('',views.blog_list,name='blog_list'),
    path('blog/<slug>/',views.blog_details,name='blog_details'),
    path('<slug:category_slug>/', views.category, name='blog_by_category'),
    path('search/', views.search_blog, name='search_blog'),
    
    
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('blog.urls',namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL,
    document_root= settings. MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category (models.Model):
    name =models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
    unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:blog_by_category", args={
        self.slug
        })

class Post (models.Model):
    title = models.CharField(max_length=80)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete= models.CASCADE, related_name='posts')
    slug =models.SlugField()
    thumbnail= models.ImageField(upload_to ='blog/photo/')
    description = models.TextField()
    short_description =models.TextField()
    tages= TaggableManager()
    creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
          return self .title


     

    def get_absolute_url(self):
         return reverse("blog:blog_details", kwargs={
              "slug": self.slug
              })
    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()



class Comment(models.Model):
    
    post = models.ForeignKey(Post, on_delete= models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

blog/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from.forms import CommentForm
from django.http import HttpResponseRedirect
from.models import Post,Category
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import redirect

# Create your views here.

def blog_list (request):
    categories = Category.objects.all()
    posts=Post.objects.all()

    paginator=Paginator(posts,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context ={
        'posts':posts,
        'page_obj':page_obj,
        'categories':categories,
    }
    return render (request,'blog/index.html',context)


def blog_details (request,slug):
    post=Post.objects.get (slug=slug)
    comments = post.comments.all()
    categories = Category.objects.all()
    similar_post = post.tages.similar_objects()[:4]

     
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            # redirect to a new URL:
            messages.success(request, 'Your comment submitted.')
            return HttpResponseRedirect(request.path_info)
    # if a GET (or any other method) we'll create a blank form
    else:
        comment_form = CommentForm()

    context ={
        'post':post,
        'comments':comments,
        'categories':categories,
        'similar_post':similar_post,
    }
    return render (request,'blog/details.html',context)



def category (request, category_slug=None):
    category = None
    categories = Category.objects.all()
    posts = Post.objects.all()
    latest_post= Post.objects.all()[:3]

    paginator=Paginator(posts,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        posts = posts.filter(category=category)

        paginator=Paginator(posts,3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

    context={
        'posts':posts,
        'category': category,
        'categories': categories,
        'latest_post':latest_post,
        'page_obj':page_obj,


    }

    return render (request,'blog/category.html',context)


def search_blog(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    categories = Category.objects.all()
    latest_post= Post.objects.all()[:3]
    
    paginator = Paginator(queryset, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if query:
        queryset=queryset.filter(
            Q(title__icontains=query) | Q(short_description__icontains=query) |
            Q(description__icontains=query)

        ).distinct()
    context = {
        "queryset":queryset,
        'query':query,
        'categories':categories,
        'latest_post':latest_post,
        'page_obj':page_obj

    }
    return render(request,'blog/search.html', context)

templates/blog/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Category</h1>
</body>
</html>

templates/blog/index.html
{% load static  %}
<!doctype html>
<html lang="en">

<head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- favicon -->
    <link rel="icon" sizes="16x16" href="{% static 'tamplates/assets/img/favicon.png' %}">

    <!-- Title -->
    <title> NoonPost. - Personal Blog HTML Template </title>

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"  />


    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/elegant-font-icons.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/owl.carousel.css' %}">

    <!-- main style -->
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/custom.css' %}">
</head>

<body>
    <!--loading -->
    <div class="loading">
        <div class="circle"></div>
    </div>
    <!--/-->

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <!--logo-->
            <div class="logo">
                <a href="index.html">
                    <img src="{% static 'tamplates/assets/img/logo-dark.png' %}" alt="" class="logo-dark">
                    <img src="{% static 'tamplates/assets/img/logo-white.png' %}" alt="" class="logo-white">
                </a>
            </div><!--/-->
        
            <!--navbar-collapse-->
            <div class="collapse navbar-collapse" id="main_nav">
                <ul class="navbar-nav ml-auto mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link " href="/" > Home </a>
                       
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="" > Blog </a>
                       
                    </li>
                   
                   
                    <li class="nav-item ">
                        <a class="nav-link " href="#" >Page </a>
                      
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"> Contact </a>
                    </li>
                    
                </ul>
            </div><!--/-->
            
            <!--navbar-right-->
            <div class="navbar-right ml-auto">
                <div class="theme-switch-wrapper">
                    <label class="theme-switch" for="checkbox">
                        <input type="checkbox" id="checkbox" />
                        <div class="slider round"></div>
                    </label>
                </div>

                <div class="social-icones">
                    <ul class="list-inline">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>
               
                <div class="search-icon">
                    <i class="fas fa-search"></i>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
    <!--/-->

    <!--masonry-layout-->
    <section class="section masonry-layout pt-45">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-columns">
                        

						{% for post in page_obj %}
						  
						
                        <!--Post-1-->
                        <div class="card">
                            <div class="post-card">
                                <div class="post-card-image">
                                    <a href="">
                                        <img src="{{ post.thumbnail.url }}" alt="">
                                    </a>
        
                                </div>
                                <div class="post-card-content">
                                    <a href="{{ category.get_absolute_url }}" class="categorie">{{ post.category.name }} </a>
                                    <h5>
                                        <a href="{{ post.get_absolute_url }} ">{{ post.title }} </a>
                                    </h5>
                                    <p> {{ post.description }}
                                    </p>
                                    <div class="post-card-info">
                                        <ul class="list-inline">
                                           
                                          
                                            <li class="dot"></li>
                                            <li>{{ post.creation }} </li>
                                        </ul>
                                    </div>

                                   
                                </div>
                            </div>
                            

                        </div>
                        <!--/-->
						{% endfor %}
        
                       
                       <!--widget-categories-->
       
        
        
        
                    </div>
                    <!--pagination-->
                    <div class="pagination mt-30">
                        <ul class="list-inline">

                            {% load l10n %}           
                            {% for post in page_obj.paginator.page_range %}
                            
                            {% if page_obj.number == post  %}
                            <li class="active">
                                <a href="?page={{ post }}">{{ post | localize }}</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="?page={{ post }}">{{ post }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                          
                            

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/-->

       
  
    <!--footer-->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright">
                        <p>© Copyright 2021  <a href="#">AssiaGroupe</a> , All rights reserved.</p>
                    </div>
                    <div class="back">
                        <a href="#" class="back-top">
                            <i class="arrow_up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form action="{% url 'blog:search_blog' %}" class="search-form" >
                    <input type="search" value="" name="q" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'tamplates/assets/js/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/bootstrap.min.js' %}"></script>

    <!-- JS Plugins  -->
    <script src="{% static 'tamplates/assets/js/ajax-contact.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/switch.js' %}"></script>
    
    <!-- JS main  -->
    <script src="{% static 'tamplates/assets/js/main.js' %}"></script>


</body>

</html>

templates/blog/search.html
{% load static  %}
<!doctype html>
<html lang="en">

<head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- favicon -->
    <link rel="icon" sizes="16x16" href="{% static 'tamplates/assets/img/favicon.png' %}">

    <!-- Title -->
    <title> NoonPost. - Personal Blog HTML Template </title>

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">



    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/elegant-font-icons.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/owl.carousel.css' %}">

    <!-- main style -->
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'tamplates/assets/css/custom.css' %}">
</head>

<body>
    <!--loading -->
    <div class="loading">
        <div class="circle"></div>
    </div>
    <!--/-->

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <!--logo-->
            <div class="logo">
                <a href="index.html">
                    <img src="{% static 'tamplates/assets/img/logo-dark.png' %}" alt="" class="logo-dark">
                    <img src="{% static 'tamplates/assets/img/logo-white.png' %}" alt="" class="logo-white">
                </a>
            </div><!--/-->
        
            <!--navbar-collapse-->
            <div class="collapse navbar-collapse" id="main_nav">
                <ul class="navbar-nav ml-auto mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link " href="/" > Home </a>
                       
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="" > Blog </a>
                       
                    </li>
                   
                   
                    <li class="nav-item ">
                        <a class="nav-link " href="#" >Page </a>
                      
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"> Contact </a>
                    </li>
                    
                </ul>
            </div><!--/-->
            
            <!--navbar-right-->
            <div class="navbar-right ml-auto">
                <div class="theme-switch-wrapper">
                    <label class="theme-switch" for="checkbox">
                        <input type="checkbox" id="checkbox" />
                        <div class="slider round"></div>
                    </label>
                </div>

                <div class="social-icones">
                    <ul class="list-inline">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>
               
                <div class="search-icon">
                    <i class="icon_search"></i>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
    <!--/-->

    <!--masonry-layout-->
    <section class="section masonry-layout pt-45">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-columns">
                        {% if queryset %}

						{% for post in queryset %}
						  
						
                        <!--Post-1-->
                        <div class="card">
                            <div class="post-card">
                                <div class="post-card-image">
                                    <a href="post-default.html">
                                        <img src="{{ post.thumbnail.url }}" alt="">
                                    </a>
        
                                </div>
                                <div class="post-card-content">
                                    <a href="{{category.get_absolute_url}}" class="categorie">{{ category.name }} </a>
                                    <h5>
                                        <a href="{{ post.get_absolute_url }} ">{{ post.title }} </a>
                                    </h5>
                                    <p> {{ post.description }}
                                    </p>
                                    <div class="post-card-info">
                                        <ul class="list-inline">
                                           
                                          
                                            <li class="dot"></li>
                                            <li>{{ post.creation }} </li>
                                        </ul>
                                    </div>

                                   
                                </div>
                            </div>
                            

                        </div>
                        <!--/-->
						{% endfor %}
                        {% else %}

                        <h1 style="text-align: center;"> No Result fouund </h1>
                        {% endif %}

        
                       
                       <!--widget-categories-->
       
        
        
        
                    </div>
                    <!--pagination-->
                    <div class="pagination mt-30">
                        <ul class="list-inline">

                            {% load l10n %}           
                            {% for post in page_obj.paginator.page_range %}
                            
                            {% if page_obj.number == post  %}
                            <li class="active">
                                <a href="?page={{ post }}">{{ post | localize }}</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="?page={{ post }}">{{ post }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                          
                            

                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>
    </section>
    <!--/-->

       
  
    <!--footer-->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright">
                        <p>© Copyright 2021  <a href="#">AssiaGroupe</a> , All rights reserved.</p>
                    </div>
                    <div class="back">
                        <a href="#" class="back-top">
                            <i class="arrow_up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form class="search-form" action="{% url 'blog:search_blog' %}">
                    <input type="search" value="" name="q" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'tamplates/assets/js/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/bootstrap.min.js' %}"></script>

    <!-- JS Plugins  -->
    <script src="{% static 'tamplates/assets/js/ajax-contact.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'tamplates/assets/js/switch.js' %}"></script>
    
    <!-- JS main  -->
    <script src="{% static 'tamplates/assets/js/main.js' %}"></script>


</body>

</html>